/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ngaycuoicungdihoc;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DecimalFormat;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ASUS FX504
 */
public class frmQLNhanSu extends javax.swing.JFrame {
    SQLQuery query = new SQLQuery();
    
    DefaultListModel dsChucVu = new DefaultListModel();
    
    /**
     * Creates new form frmQLNhanSu
     */
    public frmQLNhanSu() {
        initComponents();
        
        ClearContents();
        ShowJobTitles();
        ShowComboBox();
//        EnableAllContents(false);
    }
    
    private void ClearEmplyeeList(){
        DefaultTableModel model = (DefaultTableModel)tbDSNhanVien.getModel();
        model.setRowCount(0);
    }
    
    private void ShowListOfEmployee_JobTitles(String title){
        ClearEmplyeeList();
        try {
            DefaultTableModel model = (DefaultTableModel)tbDSNhanVien.getModel();
            ResultSet rs = query.GetDSNV_ChucVu(title);
            while(rs.next()) {
                String id = rs.getString("EmployeeID");
                String hoTen = rs.getString("name");
                String phone = rs.getString("Phone");
                String luong = rs.getString("PayGrade");
                double l = Double.parseDouble(luong);
                DecimalFormat formatter = new DecimalFormat("#,### VNĐ");
                luong = formatter.format(l);
                
                model.addRow(new Object[]{id, hoTen, phone, luong});
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }
    
    public boolean isNumeric(String str) { 
        try {  
            Double.parseDouble(str);  
            return true;
        } catch(NumberFormatException e){  
            return false;  
        }  
    }
    
    private void ShowComboBox(){
        cbChucVu.removeAllItems();
        try {
//            cbChucVu.addItem("");
            ResultSet rs = query.GetDSChucVu();
            while (rs.next()) {
                cbChucVu.addItem(rs.getString("JobTitles"));
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }
    
    private void ShowJobTitles(){
        dsChucVu.removeAllElements();
        try {
            ResultSet rs = query.GetDSChucVu();
            while (rs.next()) {
                dsChucVu.addElement(rs.getString("JobTitles"));
            }            
            lvDSChucVu.setModel(dsChucVu);
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }
    
    private boolean CheckExistedEmployee(String id) throws SQLException {
        ResultSet rs = query.getMaNhanVien(id);
        if (rs.next()) {
            return false;
        } 
        return true;
    }
    
    private void CheckEmployeeID(String id) throws SQLException {
        ResultSet rs = query.getNhanVienFromMa(id);
        if (rs.next()){
//            System.out.println("Result : " + rs.getString("Phone"));
            txtTen.setText(rs.getString("name"));
            txtLuong.setText(rs.getString("PayGrade"));
            txtSDT.setText(rs.getString("Phone"));
            txtTenLD.setText(rs.getString("ManagerName"));
            cbChucVu.setSelectedItem(rs.getString("JobTitles"));
        }else {
            txtTen.setText("");
            txtLuong.setText("");
            txtSDT.setText("");
            txtTenLD.setText("");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lvDSChucVu = new javax.swing.JList<>();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbDSNhanVien = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtTen = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtSDT = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtLuong = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtTenLD = new javax.swing.JTextField();
        cbChucVu = new javax.swing.JComboBox<>();
        btnThem = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Quản lý nhân sự");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Danh sách chức vụ"));
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.LINE_AXIS));

        lvDSChucVu.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        lvDSChucVu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lvDSChucVuMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(lvDSChucVu);

        jPanel1.add(jScrollPane1);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Danh sách nhân viên"));
        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.LINE_AXIS));

        tbDSNhanVien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Họ và tên", "SĐT", "Lương"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbDSNhanVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbDSNhanVienMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbDSNhanVien);
        if (tbDSNhanVien.getColumnModel().getColumnCount() > 0) {
            tbDSNhanVien.getColumnModel().getColumn(0).setPreferredWidth(10);
            tbDSNhanVien.getColumnModel().getColumn(2).setPreferredWidth(30);
            tbDSNhanVien.getColumnModel().getColumn(3).setPreferredWidth(30);
        }

        jPanel2.add(jScrollPane2);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Thông tin nhân viên"));

        jLabel2.setText("Chức vụ");

        jLabel3.setText("ID");

        txtID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtIDKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtIDKeyReleased(evt);
            }
        });

        jLabel4.setText("Họ và tên");

        jLabel5.setText("SĐT");

        jLabel6.setText("Lương");

        jLabel7.setText("Tên lãnh đạo");

        cbChucVu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnThem.setText("Thêm");
        btnThem.setEnabled(false);
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnSua.setText("Sửa");
        btnSua.setEnabled(false);
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnXoa.setText("Xóa");
        btnXoa.setEnabled(false);
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(196, Short.MAX_VALUE)
                .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(166, 166, 166))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(155, 155, 155)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(36, 36, 36)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(cbChucVu, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtID, javax.swing.GroupLayout.DEFAULT_SIZE, 232, Short.MAX_VALUE)
                                    .addComponent(txtTen)
                                    .addComponent(txtSDT)
                                    .addComponent(txtLuong)
                                    .addComponent(txtTenLD))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addContainerGap())))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cbChucVu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtSDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtTenLD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThem)
                    .addComponent(btnSua)
                    .addComponent(btnXoa))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        // TODO add your handling code here:
//        int row = tbDSNhanVien.getSelectedRow();
        String id = txtID.getText();
        String name = txtTen.getText();
        String supName = txtTenLD.getText();
        String phone = txtSDT.getText();
        String pay = txtLuong.getText();
        String jobName = cbChucVu.getSelectedItem().toString();
        String[] arrOfString = name.split(" ", 2);
        String fname = arrOfString[1];
        String lname = arrOfString[0];
        
        try{
            if (isNumeric(pay) && isNumeric(phone)) {
                query.UpdateNhanVien(id, fname, lname, phone, jobName, pay, supName);
                JOptionPane.showMessageDialog(this, "Sửa thành công");
            } else {
                JOptionPane.showMessageDialog(this, "Số điện thoại và tiền lương phải là kiểu số", "Lỗi nhập", JOptionPane.ERROR_MESSAGE);
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
        ShowListOfEmployee_JobTitles(lvDSChucVu.getSelectedValue().toString());
    }//GEN-LAST:event_btnSuaActionPerformed

    private void lvDSChucVuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lvDSChucVuMouseClicked
        // TODO add your handling code here:
        String chucvu = lvDSChucVu.getSelectedValue().toString();
        ShowListOfEmployee_JobTitles(chucvu);
    }//GEN-LAST:event_lvDSChucVuMouseClicked

    private void tbDSNhanVienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbDSNhanVienMouseClicked
        // TODO add your handling code here:
        int index = tbDSNhanVien.getSelectedRow();
        String id = tbDSNhanVien.getValueAt(index, 0).toString();
        
        btnSua.setEnabled(true);
        btnXoa.setEnabled(true);
        btnThem.setEnabled(false);
        
        try {
            ResultSet rs = query.GetNhanVien_ID(id);
            rs.next();
            
            String name = rs.getString("name");
            String phone = rs.getString("Phone");
            String luong = rs.getString("PayGrade");
            String tenLD = rs.getString("ManagerName");
            String chucvu = rs.getString("JobTitles");
            
            ClearContents();
            ShowComboBox();
            cbChucVu.setSelectedItem(chucvu);
            txtID.setText(id);
            txtTen.setText(name);
            txtSDT.setText(phone);
            txtLuong.setText(luong);
            txtTenLD.setText(tenLD);
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_tbDSNhanVienMouseClicked

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        if (txtID.getText().equals("") || txtTen.getText().equals("") || txtLuong.getText().equals("") || txtSDT.getText().equals("") || txtTenLD.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Xin nhập đủ thông tin", "Lỗi nhập", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        String id = txtID.getText();
        String name = txtTen.getText();
        String supName = txtTenLD.getText();
        String phone = txtSDT.getText();
        String pay = txtLuong.getText();
        String jobName = cbChucVu.getSelectedItem().toString();
        String[] arrOfString = name.split(" ", 2);
        String fname = arrOfString[1];
        String lname = arrOfString[0];
        
        try {
            if (arrOfString.length < 2) {
                JOptionPane.showMessageDialog(this, "Tên nhập chưa hợp lệ", "Lỗi nhập", JOptionPane.ERROR_MESSAGE);
            }else if (CheckExistedEmployee(id)) {
                if (isNumeric(pay) && isNumeric(phone)) {
                    query.AddNhanVien(id, fname, lname, phone, jobName, pay, supName);
                    JOptionPane.showMessageDialog(this, "Thêm thành công nhân viên " + name);
                    btnThem.setEnabled(false);
                    btnSua.setEnabled(true);
                    btnXoa.setEnabled(true);                    
                } else {
                    JOptionPane.showMessageDialog(this, "Số điện thoại và tiền lương phải là kiểu số", "Lỗi nhập", JOptionPane.ERROR_MESSAGE);
                }
//                JOptionPane.showMessageDialog(this, "Duoc them", "Lỗi nhập", JOptionPane.ERROR_MESSAGE);

            } else {
                JOptionPane.showMessageDialog(this, "Mã nhân viên đã tồn tại.\nXin nhập mã mới", "Lỗi nhập", JOptionPane.ERROR_MESSAGE);
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
        ShowJobTitles();
        ShowListOfEmployee_JobTitles(cbChucVu.getSelectedItem().toString());
    }//GEN-LAST:event_btnThemActionPerformed

    private void txtIDKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIDKeyPressed
        // TODO add your handling code here:
//        try {
//            CheckEmployeeID(txtID.getText());
//        } catch (SQLException e) {
//            e.printStackTrace();
//        }
    }//GEN-LAST:event_txtIDKeyPressed

    private void txtIDKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIDKeyReleased
        // TODO add your handling code here:
        try {
            CheckEmployeeID(txtID.getText());
            if (CheckExistedEmployee(txtID.getText())) {
                btnThem.setEnabled(true);
                btnXoa.setEnabled(false);
                btnSua.setEnabled(false);
            } else {
                btnThem.setEnabled(false);
                btnXoa.setEnabled(true);
                btnSua.setEnabled(true);
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_txtIDKeyReleased

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        try {
            if (!CheckExistedEmployee(txtID.getText())){
                int answer = JOptionPane.showConfirmDialog(this, "Xác nhận xóa ?", "Xóa", JOptionPane.YES_NO_OPTION);
                if (answer == JOptionPane.YES_OPTION){
                    query.RemoveNhanVien(txtID.getText());  
                    ShowListOfEmployee_JobTitles(cbChucVu.getSelectedItem().toString());
                    ClearContents();
                    btnXoa.setEnabled(false);
                    btnSua.setEnabled(false);
                }
            } 
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void ClearContents(){
        txtID.setText("");
        txtLuong.setText("");
        txtSDT.setText("");
        txtTen.setText("");
        txtTenLD.setText("");
        
        cbChucVu.setSelectedIndex(0);
    }
    
    private void EnableAllContents(boolean enable){
        txtID.setEnabled(enable);
        txtLuong.setEnabled(enable);
        txtSDT.setEnabled(enable);
        txtTen.setEnabled(enable);
        txtTenLD.setEnabled(enable);
        
        cbChucVu.setEnabled(enable);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmQLNhanSu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmQLNhanSu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmQLNhanSu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmQLNhanSu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmQLNhanSu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JComboBox<String> cbChucVu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<String> lvDSChucVu;
    private javax.swing.JTable tbDSNhanVien;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtLuong;
    private javax.swing.JTextField txtSDT;
    private javax.swing.JTextField txtTen;
    private javax.swing.JTextField txtTenLD;
    // End of variables declaration//GEN-END:variables
}
